### ISSUE TITLE
Black precommit action does not autoformat the code for you

### ISSUE THREAD

**Issue by LBlend** [UiO-Gaming/uiogaming-bot#14]
The "black formatting" stage of the precommit action only runs black to ensure that the pushed code is the same as how black would format it, not that it satisfies the linter's rules. This means that the precommit does not fix the code for you, and you have to run black locally before commiting to make sure the action tests don't fail. This is really annoying behaviour

**Comment by marksverdhei** [comment]
Run pre-commit locally
if you have pre-commit installed it will prevent committing before all checks are fixed. 
As it is run, the formatting changes are made and you'll have to stage all the changes black made before committing again.

Run ´pre-commit install´ to add the git hook
or run ´pre-commit run -a´ to run the hooks manually. I do the latter one myself, for the most part
