### ISSUE TITLE
Add support for attachments in "the" command

### ISSUE THREAD

**Issue by LBlend** [UiO-Gaming/uiogaming-bot#17]
Slash commands support files, which means we can replace the url parameter with a file parameter

![image](https://user-images.githubusercontent.com/24893890/236620670-1405c8ae-798d-42fa-afff-3151d2867269.png)

```python
@commands.command()
async def yeet(self, image: discord.Attachment):
    ...
```

**Comment by LBlend** [comment]
@marksverdhei yay or nay?

**Comment by marksverdhei** [comment]
LFG!!!

**Comment by LBlend** [comment]
I added a new util function that can read attachments and return a BytesIO object. I haven't tested it yet because I'm lazy like that but you can assume it works

https://github.com/UiO-Gaming/uiogaming-bot/blob/442b541927ce48069e9d8cbe9c8f11e3f79b933e/src/cogs/meme.py#L32-L45
